"""
Report Engine — HTML/CSV/JSON/PDF/XLSX Ausgabe
===============================================
Generiert Reports aus Query-Ergebnissen.

Unterstützte Formate (v2.0):
  html  — Vollständige HTML-Mail mit Branding + CSS-Balkendiagramme (email-kompatibel)
  csv   — Kommagetrennte Werte
  json  — Rohdaten als JSON
  pdf   — fpdf2 (pip install fpdf2)
  xlsx  — openpyxl (pip install openpyxl)

v2.0.0 (2026-04-11) — breaking changes:
  - i18n-aware: alle Labels kommen aus einem `labels`-Dict. Ohne Dict wird
    Englisch als sinnvoller Default verwendet (vorher war alles hardcoded
    Deutsch). Siehe feedback_reports_i18n.md.
  - Design-System: Layout nutzt Themes, Typography, Header-Varianten, Density,
    Charts-Styles aus design_presets.py. `normalize_layout()` im Aufrufer
    sorgt für Defaults.
  - Base64-Logos: `layout.logo_base64` wird als data-URI eingebettet
    (legacy `layout.logo_url` wird noch unterstützt, falls base64 leer).
  - Environmental Impact Section (optional, über `layout.show_env_impact`).
  - Period-over-period Comparison Section (optional, über
    `layout.show_period_comparison` + Trend-Daten im Report).
  - Neue öffentliche Funktion `compute_env_impact(total_pages, duplex_pages)`.

Das alte Verhalten (ohne `labels`) bleibt kompatibel — dann werden englische
Labels verwendet. Aufrufer sollten aber immer ein `labels`-Dict übergeben,
damit Reports in der UI-Sprache des Benutzers erscheinen.
"""

import csv
import io
import json
import logging
from datetime import datetime
from typing import Any, Callable, Optional

logger = logging.getLogger(__name__)

try:
    from jinja2 import Environment, BaseLoader
    JINJA2_AVAILABLE = True
except ImportError:
    JINJA2_AVAILABLE = False
    logger.warning("jinja2 nicht installiert — HTML-Reports nicht verfügbar")

from .design_presets import (
    normalize_layout,
    FONTS_BY_KEY,
    CURRENCIES_BY_KEY,
)


# ─── i18n Label-Lookup ───────────────────────────────────────────────────────
#
# Alle Reports benutzen `_lbl(labels, key, fallback)` statt hardcoded Strings.
# Wenn der Aufrufer (Scheduler/Preview) ein `labels`-Dict übergibt, kommen
# die Werte aus der aktiven UI-Sprache. Ohne Dict nutzen wir _LBL_DEFAULTS
# (Englisch).
#
# Wichtig: der Dict-Key ist der rpt_eng_*-Key — das Label selbst ist der
# übersetzte String. Der Scheduler baut das Dict aus der i18n.TRANSLATIONS
# der Benutzer-Locale.

_LBL_DEFAULTS: dict[str, str] = {
    # Titles — Stufe 1
    "rpt_eng_title_print_stats":       "Print Volume Report",
    "rpt_eng_title_cost_report":       "Cost Report",
    "rpt_eng_title_top_users":         "Top Users",
    "rpt_eng_title_top_printers":      "Top Printers",
    "rpt_eng_title_trend":             "Trend Analysis",
    "rpt_eng_title_anomalies":         "Anomalies",
    # Titles — Stufe 2 (v6.5.0: Defaults ergänzt damit keine rohen i18n-Keys
    # mehr angezeigt werden wenn die User-Locale den Key nicht hat)
    "rpt_eng_title_printer_history":   "Printer History Report",
    "rpt_eng_title_device_readings":   "Printer Service Status Report",
    "rpt_eng_title_job_history":       "Job History Report",
    "rpt_eng_title_queue_stats":       "Queue Overview",
    "rpt_eng_title_user_detail":       "User Print Details",
    "rpt_eng_title_user_copy_detail":  "User Copy Details",
    "rpt_eng_title_user_scan_detail":  "User Scan Details",
    "rpt_eng_title_workstation_overview": "Workstation Overview",
    "rpt_eng_title_workstation_detail":   "Workstation Details",
    "rpt_eng_title_tree_meter":        "Sustainability Report",
    "rpt_eng_title_service_desk":      "Service Desk Report",
    "rpt_eng_title_sensitive_documents": "Sensitive Documents",
    "rpt_eng_title_hour_dow_heatmap":  "Usage Heatmap: Hour × Weekday",
    "rpt_eng_title_audit_log":         "Admin Audit Trail",
    "rpt_eng_title_off_hours_print":   "Off-Hours Printing",
    # Period / header
    "rpt_eng_period":              "Period",
    "rpt_eng_generated_at":        "Generated",
    "rpt_eng_footer_default":      "Automatically generated by Printix MCP Reporting",
    # KPI labels
    "rpt_eng_kpi_total_pages":     "Total pages",
    "rpt_eng_kpi_color_pages":     "Color pages",
    "rpt_eng_kpi_bw_pages":        "B/W pages",
    "rpt_eng_kpi_duplex_pct":      "Duplex rate",
    "rpt_eng_kpi_total_jobs":      "Jobs",
    "rpt_eng_kpi_total_cost":      "Total cost",
    "rpt_eng_kpi_toner_color":     "Toner cost (color)",
    "rpt_eng_kpi_toner_bw":        "Toner cost (B/W)",
    "rpt_eng_kpi_paper":           "Paper cost",
    "rpt_eng_kpi_saved_sheets":    "Sheets saved (duplex)",
    "rpt_eng_kpi_active_users":    "Active users",
    "rpt_eng_kpi_most_pages":      "Most pages",
    # Columns
    "rpt_eng_col_date":            "Date",
    "rpt_eng_col_week":            "Week",
    "rpt_eng_col_month":           "Month",
    "rpt_eng_col_period":          "Period",
    "rpt_eng_col_jobs":            "Jobs",
    "rpt_eng_col_pages":           "Pages",
    "rpt_eng_col_color":           "Color",
    "rpt_eng_col_bw":              "B/W",
    "rpt_eng_col_color_pct":       "Color %",
    "rpt_eng_col_duplex_pct":      "Duplex %",
    "rpt_eng_col_cost":            "Cost",
    "rpt_eng_col_user":            "User",
    "rpt_eng_col_dept":            "Department",
    "rpt_eng_col_printer":         "Printer",
    "rpt_eng_col_model":           "Model",
    "rpt_eng_col_location":        "Location",
    "rpt_eng_col_site":            "Site",
    "rpt_eng_col_p1":              "Previous",
    "rpt_eng_col_p2":              "Current",
    "rpt_eng_col_delta":           "Δ",
    "rpt_eng_col_metric":          "Metric",
    "rpt_eng_col_toner_color":     "Toner color",
    "rpt_eng_col_toner_bw":        "Toner B/W",
    "rpt_eng_col_paper":           "Paper",
    "rpt_eng_col_total":           "Total",
    # Sections
    "rpt_eng_section_summary":     "Summary",
    "rpt_eng_section_details":     "Details",
    "rpt_eng_section_top_users":   "Top Users",
    "rpt_eng_section_top_printers":"Top Printers",
    "rpt_eng_section_trend":       "Trend",
    "rpt_eng_section_env_impact":  "Environmental Impact",
    # Env impact
    "rpt_eng_env_title":           "Environmental Impact",
    "rpt_eng_env_co2":             "CO₂ emissions (kg)",
    "rpt_eng_env_trees":           "Trees (equivalent)",
    "rpt_eng_env_water":           "Water (liters)",
    "rpt_eng_env_energy":          "Energy (kWh)",
    "rpt_eng_env_paper_kg":        "Paper (kg)",
    # Empty state
    "rpt_eng_no_data":             "No data for the selected period.",
    # Period comparison
    "rpt_eng_vs_prev":             "vs. previous period",
    "rpt_eng_delta_up":            "▲",
    "rpt_eng_delta_down":          "▼",
}


def _lbl(labels: Optional[dict], key: str) -> str:
    """Liefert ein übersetztes Label mit sinnvollem Fallback."""
    if labels and key in labels and labels[key]:
        return labels[key]
    return _LBL_DEFAULTS.get(key, key)


# ─── Environmental Impact ────────────────────────────────────────────────────
#
# Umrechnungsfaktoren pro Seite (A4) basierend auf Industriedurchschnitten:
#   Paper:  ~5 g pro Blatt (80 g/m²)
#   Trees:  ~8333 A4-Blätter pro Baum (≈ 50 kg Reinpapier)
#   CO₂:    ~4.7 g pro Blatt (Produktion + Transport + Druck)
#   Water:  ~10 l pro Blatt (Zellstoff-Produktion)
#   Energy: ~50 Wh pro Blatt (Druck + Gerät)
#
# Bei Duplex-Seiten wird kein zusätzliches Blatt, aber die Hälfte pro
# "ausgegebene Seite" gezählt — das spart Papier/Bäume/Wasser, nicht aber
# Toner und Energie. Wir rechnen die Einsparung über `saved_sheets` direkt
# ab: jede eingesparte Seite zählt −100 % Papier/CO₂/Wasser/Bäume.

_ENV_FACTORS = {
    "paper_g_per_sheet":  5.0,        # Gramm pro A4-Blatt
    "sheets_per_tree":    8333.0,     # A4-Blätter pro Baum
    "co2_g_per_sheet":    4.7,        # Gramm CO₂ pro Blatt
    "water_l_per_sheet":  10.0,       # Liter Wasser pro Blatt
    "energy_wh_per_sheet":50.0,       # Wattstunden pro Blatt
}


def compute_env_impact(
    total_pages: int,
    duplex_pages: int = 0,
    saved_sheets: int = 0,
) -> dict[str, float]:
    """
    Berechnet die Umweltwirkung der ausgedruckten Seiten.

    Args:
        total_pages:  Gesamt gedruckte Seiten (Farb + S/W)
        duplex_pages: Davon Duplex-Seiten (zur Info, nicht direkt genutzt)
        saved_sheets: Eingesparte Blätter durch Duplex (positiv = gut)

    Returns:
        Dict mit den Schlüsseln: paper_kg, trees, co2_kg, water_l, energy_kwh.
        Alle Werte sind **nach** Abzug der Einsparungen durch Duplex.
    """
    tp = max(int(total_pages or 0), 0)
    ss = max(int(saved_sheets or 0), 0)
    # Netto-Blätter: total_pages ist seitenbasiert, saved_sheets ist blattbasiert.
    # Bei Duplex: 2 Seiten = 1 Blatt, sonst 1 Seite = 1 Blatt. Die Einsparung
    # sagt uns direkt, wieviele Blätter NICHT gedruckt wurden.
    physical_sheets = max(tp - ss, 0)

    paper_g   = physical_sheets * _ENV_FACTORS["paper_g_per_sheet"]
    trees     = physical_sheets / _ENV_FACTORS["sheets_per_tree"]
    co2_g     = physical_sheets * _ENV_FACTORS["co2_g_per_sheet"]
    water_l   = physical_sheets * _ENV_FACTORS["water_l_per_sheet"]
    energy_wh = physical_sheets * _ENV_FACTORS["energy_wh_per_sheet"]

    return {
        "paper_kg":    round(paper_g / 1000, 2),
        "trees":       round(trees, 3),
        "co2_kg":      round(co2_g / 1000, 2),
        "water_l":     round(water_l, 1),
        "energy_kwh":  round(energy_wh / 1000, 2),
        "sheets_used": physical_sheets,
        "sheets_saved": ss,
    }


def _build_env_impact_section(
    env: dict[str, float],
    labels: Optional[dict] = None,
) -> dict[str, Any]:
    """Baut eine Report-Section mit Umweltwirkungs-Metriken."""
    return {
        "title":   _lbl(labels, "rpt_eng_env_title"),
        "columns": [_lbl(labels, "rpt_eng_col_metric"), _lbl(labels, "rpt_eng_col_total")],
        "rows": [
            [_lbl(labels, "rpt_eng_env_paper_kg"), f"{env['paper_kg']:,.2f}"],
            [_lbl(labels, "rpt_eng_env_trees"),    f"{env['trees']:,.3f}"],
            [_lbl(labels, "rpt_eng_env_co2"),      f"{env['co2_kg']:,.2f}"],
            [_lbl(labels, "rpt_eng_env_water"),    f"{env['water_l']:,.0f}"],
            [_lbl(labels, "rpt_eng_env_energy"),   f"{env['energy_kwh']:,.2f}"],
        ],
        "chart": {},
    }


# ─── HTML Template ────────────────────────────────────────────────────────────

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="{{ lang }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ title }}</title>
<style>
  body        { font-family: {{ font_css }}; font-size: {{ font_size_base }}px; color: {{ text_color }}; margin: 0; padding: 0; background: #f0f1f4; }
  .wrapper    { max-width: 920px; margin: 20px auto; background: {{ background_color }}; border-radius: 6px; overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,.14); }
  {%- if header_variant == 'banner' %}
  .header     { background: {{ primary_color }}; color: #fff; padding: 36px 40px; text-align: left; }
  .header h1  { margin: 0 0 6px; font-size: {{ font_size_h1 }}px; font-weight: 700; letter-spacing: .3px; }
  .header p   { margin: 0; opacity: .9; font-size: 13px; }
  .header-row { display: flex; align-items: center; justify-content: space-between; gap: 24px; }
  .header-logo{ max-height: 64px; max-width: 180px; object-fit: contain; background: rgba(255,255,255,.12); padding: 6px; border-radius: 4px; }
  {%- elif header_variant == 'center' %}
  .header     { background: {{ primary_color }}; color: #fff; padding: 28px 32px; text-align: center; }
  .header h1  { margin: 12px 0 4px; font-size: {{ font_size_h1 }}px; font-weight: 600; }
  .header p   { margin: 0; opacity: .85; font-size: 13px; }
  .header-logo{ max-height: 56px; max-width: 160px; object-fit: contain; margin: 0 auto; display: block; }
  {%- elif header_variant == 'minimal' %}
  .header     { background: {{ background_color }}; color: {{ text_color }}; padding: 24px 32px; border-bottom: 3px solid {{ primary_color }}; display: flex; align-items: center; justify-content: space-between; gap: 20px; }
  .header h1  { margin: 0 0 4px; font-size: {{ font_size_h1 }}px; font-weight: 600; color: {{ primary_color }}; }
  .header p   { margin: 0; color: {{ muted_color }}; font-size: 13px; }
  .header-logo{ max-height: 56px; max-width: 160px; object-fit: contain; }
  {%- else %}
  .header     { background: {{ primary_color }}; color: #fff; padding: 24px 32px; display: flex; align-items: flex-start; justify-content: space-between; gap: 20px; }
  .header-text{ flex: 1; }
  .header h1  { margin: 0 0 4px; font-size: {{ font_size_h1 }}px; font-weight: 600; }
  .header p   { margin: 0; opacity: .85; font-size: 13px; }
  .header-logo{ max-height: 56px; max-width: 160px; object-fit: contain; align-self: center; border-radius: 4px; }
  {%- endif %}
  .content    { padding: {{ density_padding }}px 32px; }
  .kpi-row    { display: flex; gap: 16px; margin-bottom: {{ density_gap }}px; flex-wrap: wrap; }
  .kpi-card   { flex: 1; min-width: 140px; background: {{ table_alt_bg }}; border-left: 4px solid {{ accent_color }}; padding: 14px 18px; border-radius: 4px; }
  .kpi-card .label { font-size: 11px; text-transform: uppercase; color: {{ muted_color }}; letter-spacing: .5px; }
  .kpi-card .value { font-size: 24px; font-weight: 700; color: {{ primary_color }}; margin-top: 4px; }
  .kpi-card .sub   { font-size: 11px; color: {{ muted_color }}; margin-top: 2px; }
  h2          { font-size: {{ font_size_h2 }}px; font-weight: 600; color: {{ text_color }}; margin: {{ density_gap }}px 0 10px; border-bottom: 2px solid {{ primary_color }}; padding-bottom: 6px; }
  table       { width: 100%; border-collapse: collapse; font-size: 12px; margin-bottom: 16px; }
  th          { background: {{ table_header_bg }}; color: #fff; padding: 8px 12px; text-align: left; font-weight: 600; }
  td          { padding: {{ density_cell_py }}px 12px; border-bottom: 1px solid #eee; color: {{ text_color }}; }
  tr:nth-child(even) td { background: {{ table_alt_bg }}; }
  .delta-pos  { color: #d32f2f; font-weight: 600; }
  .delta-neg  { color: #2e7d32; font-weight: 600; }
  .delta-neu  { color: {{ muted_color }}; }
  .badge      { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: 600; }
  .badge-ok   { background: #e8f5e9; color: #2e7d32; }
  .badge-warn { background: #fff3e0; color: #e65100; }
  .footer     { background: {{ table_alt_bg }}; padding: 14px 32px; font-size: 11px; color: {{ muted_color }}; border-top: 1px solid #ddd; }
  .chart-wrap  { margin: 0 0 {{ density_gap }}px; }
  .chart-title { font-size: 12px; font-weight: 600; color: {{ muted_color }}; margin: 0 0 8px; text-transform: uppercase; letter-spacing: .4px; }
  .chart-tbl   { width: 100%; border-collapse: collapse; }
  .chart-tbl .cl { width: 130px; font-size: 11px; color: {{ muted_color }}; padding: 3px 10px 3px 0; white-space: nowrap; vertical-align: middle; max-width: 130px; overflow: hidden; }
  .chart-tbl .cb { padding: 3px 6px; vertical-align: middle; }
  .bar-bg      { width: 100%; height: 16px; background: #eee; border-radius: 3px; }
  {%- if chart_style == 'minimal' %}
  .bar         { height: 4px; margin-top: 6px; border-radius: 2px; min-width: 3px; display: block; }
  .bar-bg      { background: transparent; height: 16px; }
  {%- else %}
  .bar         { height: 16px; border-radius: 3px; min-width: 3px; display: block; }
  {%- endif %}
  .chart-tbl .cv { width: 80px; font-size: 11px; color: {{ text_color }}; font-weight: 600; padding: 3px 0 3px 8px; text-align: right; white-space: nowrap; vertical-align: middle; }
  .chart-svg   { text-align: center; margin: 4px 0 4px; }
  .chart-svg svg { max-width: 100%; height: auto; }
  .chart-legend{ margin-top: 8px; font-size: 11px; color: {{ muted_color }}; }
  .legend-item { display: inline-block; margin-right: 14px; white-space: nowrap; }
  .legend-swatch { display:inline-block; width:10px; height:10px; border-radius:2px; vertical-align:middle; margin-right:4px; }
  .legend-val  { color: {{ text_color }}; font-weight: 600; margin-left: 2px; }
  .kpi-spark   { margin-top: 4px; height: 24px; line-height: 0; }
  .kpi-spark svg { display: block; }
</style>
</head>
<body>
<div class="wrapper">
  <div class="header">
    {%- if header_variant == 'center' %}
      {%- if logo_src %}<img class="header-logo" src="{{ logo_src }}" alt="Logo">{% endif %}
      <h1>{{ title }}</h1>
      <p>{{ company_name }}{% if company_name %} &nbsp;|&nbsp; {% endif %}{{ period_label }}: {{ period }} &nbsp;|&nbsp; {{ generated_label }}: {{ generated_at }}</p>
    {%- elif header_variant == 'banner' %}
      <div class="header-row">
        <div>
          <h1>{{ title }}</h1>
          <p>{{ company_name }}{% if company_name %} &nbsp;|&nbsp; {% endif %}{{ period_label }}: {{ period }} &nbsp;|&nbsp; {{ generated_label }}: {{ generated_at }}</p>
        </div>
        {%- if logo_src %}<img class="header-logo" src="{{ logo_src }}" alt="Logo">{% endif %}
      </div>
    {%- elif header_variant == 'minimal' %}
      <div>
        <h1>{{ title }}</h1>
        <p>{{ company_name }}{% if company_name %} &nbsp;|&nbsp; {% endif %}{{ period_label }}: {{ period }} &nbsp;|&nbsp; {{ generated_label }}: {{ generated_at }}</p>
      </div>
      {%- if logo_src %}<img class="header-logo" src="{{ logo_src }}" alt="Logo">{% endif %}
    {%- else %}
      <div class="header-text">
        <h1>{{ title }}</h1>
        <p>{{ company_name }}{% if company_name %} &nbsp;|&nbsp; {% endif %}{{ period_label }}: {{ period }} &nbsp;|&nbsp; {{ generated_label }}: {{ generated_at }}</p>
      </div>
      {%- if logo_src %}<img class="header-logo" src="{{ logo_src }}" alt="Logo">{% endif %}
    {%- endif %}
  </div>
  <div class="content">

  {%- if kpis %}
  <div class="kpi-row">
    {%- for kpi in kpis %}
    <div class="kpi-card">
      <div class="label">{{ kpi.label }}</div>
      <div class="value">{{ kpi.value }}</div>
      {%- if kpi.sparkline and kpi.sparkline.svg and charts_enabled and chart_style != 'none' %}
      <div class="kpi-spark">{{ kpi.sparkline.svg | safe }}</div>
      {%- endif %}
      {%- if kpi.sub %}<div class="sub">{{ kpi.sub }}</div>{% endif %}
    </div>
    {%- endfor %}
  </div>
  {%- endif %}

  {%- for section in sections %}
  <h2>{{ section.title }}</h2>
  {%- if section.chart and charts_enabled and chart_style != 'none' %}
  <div class="chart-wrap">
    {%- if section.chart.title %}<div class="chart-title">{{ section.chart.title }}</div>{% endif %}
    {%- if section.chart.type == 'svg' %}
    <div class="chart-svg">{{ section.chart.svg | safe }}</div>
      {%- if section.chart.legend %}
      <div class="chart-legend">
        {%- for l in section.chart.legend %}
        <span class="legend-item"><span class="legend-swatch" style="background:{{ l.color }}"></span>{{ l.label }} <span class="legend-val">{{ l.value }} ({{ l.pct }}%)</span></span>
        {%- endfor %}
      </div>
      {%- endif %}
    {%- else %}
    <table class="chart-tbl">
      {%- for item in section.chart.bars %}
      <tr>
        <td class="cl" title="{{ item.label }}">{{ item.label | truncate(20, True, '…', 0) }}</td>
        <td class="cb"><div class="bar-bg"><div class="bar" style="width:{{ item.pct }}%;background:{{ primary_color }}"></div></div></td>
        <td class="cv">{{ item.value }}</td>
      </tr>
      {%- endfor %}
    </table>
    {%- endif %}
  </div>
  {%- endif %}
  {%- if section.rows %}
  <table>
    <thead><tr>
      {%- for col in section.columns %}<th>{{ col }}</th>{% endfor %}
    </tr></thead>
    <tbody>
      {%- for row in section.rows %}
      <tr>
        {%- for cell in row %}<td>{{ cell }}</td>{% endfor %}
      </tr>
      {%- endfor %}
    </tbody>
  </table>
  {%- elif not section.chart %}
  <p style="color:{{ muted_color }}">{{ no_data_label }}</p>
  {%- endif %}
  {%- endfor %}

  </div>
  <div class="footer">
    {{ footer_text or footer_default }} &nbsp;|&nbsp; Printix MCP Report Engine &nbsp;|&nbsp; {{ generated_at }}
  </div>
</div>
</body>
</html>"""


# ─── Spalten-Übersetzung (v3.7.10) ────────────────────────────────────────────
#
# Mapping von DB-Spaltennamen (SQL `AS …` Aliase aus query_tools.py) auf
# menschenlesbare Labels pro Sprache. Für Sprachen, die hier nicht gepflegt
# sind, fällt `_translate_col()` auf Englisch (und dann auf einen "title case
# ohne Unterstriche"-Fallback) zurück, damit es nie ein nackter DB-Name bleibt.

COLUMN_LABELS: dict[str, dict[str, str]] = {
    "de": {
        "job_id": "Auftrags-ID",
        "print_time": "Druckzeit",
        "submit_time": "Sendezeit",
        "copy_time": "Kopierzeit",
        "scan_time": "Scanzeit",
        "last_activity": "Letzte Aktivität",
        "last_occurrence": "Letztes Auftreten",
        "period": "Zeitraum",
        "start_date": "Von",
        "end_date": "Bis",
        "print_day": "Druckdatum",
        "group_key": "Gruppe",
        "status": "Status",
        "user_email": "Benutzer-E-Mail",
        "user_name": "Benutzer",
        "email": "E-Mail",
        "name": "Name",
        "department": "Abteilung",
        "printer_id": "Drucker-ID",
        "printer_name": "Drucker",
        "model_name": "Modell",
        "vendor_name": "Hersteller",
        "location": "Standort",
        "site_name": "Site",
        "workstation_id": "Workstation-ID",
        "workstation_name": "Workstation",
        "os_type": "Betriebssystem",
        "paper_size": "Papierformat",
        "page_count": "Seiten",
        "total_jobs": "Aufträge",
        "total_pages": "Seiten gesamt",
        "color": "Farbe",
        "color_pages": "Farbseiten",
        "color_pct": "Farb-%",
        "bw_pages": "S/W-Seiten",
        "duplex": "Duplex",
        "duplex_pages": "Duplex-Seiten",
        "duplex_pct": "Duplex-%",
        "simplex_pages": "Simplex-Seiten",
        "total_sheets": "Blätter gesamt",
        "total_sheets_used": "Blätter verbraucht",
        "saved_sheets_duplex": "Blätter gespart",
        "trees_saved": "Bäume gespart",
        "sheets_per_tree": "Blätter pro Baum",
        "active_days": "Aktive Tage",
        "active_users": "Aktive Benutzer",
        "avg_pages": "Ø Seiten",
        "daily_pages": "Seiten/Tag",
        "daily_jobs": "Aufträge/Tag",
        "total_copy_jobs": "Kopier-Aufträge",
        "total_scan_jobs": "Scan-Aufträge",
        "print_jobs": "Druck-Aufträge",
        "print_pages": "Druck-Seiten",
        "pct_of_total": "Anteil %",
        "total_cost": "Gesamtkosten",
        "toner_cost_color": "Tonerkosten Farbe",
        "toner_cost_bw": "Tonerkosten S/W",
        "sheet_cost": "Papierkosten",
        "cost_per_sheet": "Kosten/Blatt",
        "cost_per_color": "Kosten/Farbseite",
        "cost_per_mono": "Kosten/S/W-Seite",
        "info": "Hinweis",
        "error": "Fehler",
    },
    "en": {
        "job_id": "Job ID",
        "print_time": "Print Time",
        "submit_time": "Submit Time",
        "copy_time": "Copy Time",
        "scan_time": "Scan Time",
        "last_activity": "Last Activity",
        "last_occurrence": "Last Occurrence",
        "period": "Period",
        "start_date": "From",
        "end_date": "To",
        "print_day": "Print Day",
        "group_key": "Group",
        "status": "Status",
        "user_email": "User Email",
        "user_name": "User",
        "email": "Email",
        "name": "Name",
        "department": "Department",
        "printer_id": "Printer ID",
        "printer_name": "Printer",
        "model_name": "Model",
        "vendor_name": "Vendor",
        "location": "Location",
        "site_name": "Site",
        "workstation_id": "Workstation ID",
        "workstation_name": "Workstation",
        "os_type": "OS",
        "paper_size": "Paper Size",
        "page_count": "Pages",
        "total_jobs": "Jobs",
        "total_pages": "Total Pages",
        "color": "Color",
        "color_pages": "Color Pages",
        "color_pct": "Color %",
        "bw_pages": "B/W Pages",
        "duplex": "Duplex",
        "duplex_pages": "Duplex Pages",
        "duplex_pct": "Duplex %",
        "simplex_pages": "Simplex Pages",
        "total_sheets": "Total Sheets",
        "total_sheets_used": "Sheets Used",
        "saved_sheets_duplex": "Sheets Saved",
        "trees_saved": "Trees Saved",
        "sheets_per_tree": "Sheets per Tree",
        "active_days": "Active Days",
        "active_users": "Active Users",
        "avg_pages": "Avg Pages",
        "daily_pages": "Pages/Day",
        "daily_jobs": "Jobs/Day",
        "total_copy_jobs": "Copy Jobs",
        "total_scan_jobs": "Scan Jobs",
        "print_jobs": "Print Jobs",
        "print_pages": "Print Pages",
        "pct_of_total": "% of Total",
        "total_cost": "Total Cost",
        "toner_cost_color": "Toner Cost Color",
        "toner_cost_bw": "Toner Cost B/W",
        "sheet_cost": "Paper Cost",
        "cost_per_sheet": "Cost/Sheet",
        "cost_per_color": "Cost/Color Page",
        "cost_per_mono": "Cost/B-W Page",
        "info": "Note",
        "error": "Error",
    },
}

# Kurze Aliasse für Dialekte und nicht gepflegte Sprachen → greifen auf de/en zurück
_LANG_FALLBACK = {
    "bar": "de", "hessisch": "de", "oesterreichisch": "de", "schwiizerdütsch": "de",
    "fr": "en", "it": "en", "es": "en", "nl": "en", "no": "en", "sv": "en",
}


def _translate_col(col: str, lang: str = "de") -> str:
    """Übersetzt einen DB-Spaltennamen in die aktive Sprache.
    Fallback: <lang> → Dialekt-Quelle → en → human-readable title case."""
    if not col:
        return ""
    col_key = str(col).strip()
    table = COLUMN_LABELS.get(lang)
    if table and col_key in table:
        return table[col_key]
    fb = _LANG_FALLBACK.get(lang)
    if fb and fb in COLUMN_LABELS and col_key in COLUMN_LABELS[fb]:
        return COLUMN_LABELS[fb][col_key]
    if "en" in COLUMN_LABELS and col_key in COLUMN_LABELS["en"]:
        return COLUMN_LABELS["en"][col_key]
    return col_key.replace("_", " ").strip().title()


# ─── Formatierungshilfen ──────────────────────────────────────────────────────

def _pdf_safe(text: str) -> str:
    """
    Ersetzt Unicode-Zeichen, die von fpdf2/Helvetica (Latin-1) nicht unterstützt werden.
    Verhindert FPDFUnicodeEncodingException bei Em-Dash, Sonderzeichen etc.
    """
    replacements = {
        "\u2013": "-",    # En-Dash –
        "\u2014": "-",    # Em-Dash —
        "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"',
        "\u2026": "...",
        "\u20ac": "EUR",
        "\u00b0": " Grad", "\u00b2": "2", "\u00b3": "3",
        "\u2122": "TM", "\u00ae": "(R)", "\u00a9": "(C)",
        "\u2022": "*", "\u25cf": "*",
    }
    for uni, asc in replacements.items():
        text = text.replace(uni, asc)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _fmt_num(v, decimals=0) -> str:
    if v is None:
        return "—"
    try:
        if decimals:
            return f"{float(v):,.{decimals}f}"
        return f"{int(v):,}"
    except (TypeError, ValueError):
        return str(v)


def _fmt_pct(v) -> str:
    if v is None:
        return "—"
    return f"{float(v):.1f} %"


def _fmt_cost(v, currency="€") -> str:
    if v is None:
        return "—"
    return f"{float(v):,.2f} {currency}"


def _fmt_delta(v):
    """Formatiert einen Delta-Wert als farbigen HTML-Span.
    Gibt Markup zurueck damit autoescape=True den HTML-Code nicht escaped."""
    if v is None:
        return "—"
    sign = "▲" if v > 0 else "▼"
    css  = "delta-pos" if v > 0 else "delta-neg"
    html = f'<span class="{css}">{sign} {abs(v):.1f}%</span>'
    try:
        from markupsafe import Markup
        return Markup(html)
    except ImportError:
        return html


# ─── Chart-Hilfsfunktionen (v3.8.1: Type-Dispatcher) ─────────────────────────

def _build_chart(
    items: list[dict],
    title: str,
    max_items: int = 20,
    chart_type: str = "bar",
    **kwargs,
) -> dict:
    """
    Generische Chart-Fabrik mit Type-Dispatcher (v3.8.1).

    Unterstützte `chart_type`-Werte:
      - "bar"       Horizontale CSS-Balken (Default, rückwärtskompatibel)
      - "line"      Inline-SVG Liniendiagramm (für Zeitreihen)
      - "heatmap"   Inline-SVG 2D-Heatmap (z.B. Stunde × Wochentag)
      - "donut"     Inline-SVG Donut/Ring-Chart (für Proportionen)
      - "sparkline" Winziger Inline-SVG-Trend (z.B. in KPI-Karten)

    Args:
        items:      Liste mit {"label": str, "display": str, "raw": float}
                    oder (für heatmap) beliebige Matrix-Struktur via kwargs.
        title:      Diagrammtitel
        max_items:  Maximale Anzahl Einträge
        chart_type: Dispatcher-Key
        **kwargs:   Chart-spezifische Optionen (color, size, ...)

    Returns:
        dict mit mindestens {"type": str, "title": str}
        + typspezifischen Feldern:
          - bar:       "bars"  (Liste)
          - line/heatmap/donut/sparkline: "svg" (str, inline SVG markup)
        oder {} wenn keine Daten.
    """
    chart_type = (chart_type or "bar").lower()
    if chart_type == "line":
        return _build_chart_svg_line(items, title, max_items, **kwargs)
    if chart_type == "heatmap":
        return _build_chart_svg_heatmap(items, title, **kwargs)
    if chart_type == "donut":
        return _build_chart_svg_donut(items, title, **kwargs)
    if chart_type == "sparkline":
        return _build_chart_svg_sparkline(items, **kwargs)
    # Default: bar (backwards-compatible)
    return _build_chart_bars(items, title, max_items)


def _build_chart_bars(items: list[dict], title: str, max_items: int = 20) -> dict:
    """Horizontale CSS-Balken (wie v3.8.0 und früher)."""
    items = [i for i in items if (i.get("raw") or 0) > 0]
    if not items:
        return {}
    items = items[:max_items]
    max_val = max(i.get("raw", 0) or 0 for i in items) or 1
    return {
        "type": "bar",
        "title": title,
        "bars": [
            {
                "label": str(i["label"]),
                "value": str(i["display"]),
                "pct":   max(1, round((i.get("raw", 0) or 0) / max_val * 100)),
            }
            for i in items
        ],
    }


def _build_chart_svg_line(
    items: list[dict],
    title: str,
    max_items: int = 60,
    width: int = 640,
    height: int = 180,
    color: str = "#1976d2",
    fill: str = "#1976d244",
) -> dict:
    """
    Inline-SVG Liniendiagramm für Zeitreihen.
    items: [{"label", "display", "raw"}, ...]
    """
    items = [i for i in items if i.get("raw") is not None]
    if len(items) < 2:
        return {}
    items = items[:max_items]
    vals = [float(i.get("raw") or 0) for i in items]
    vmax = max(vals) or 1.0
    vmin = min(vals)
    span = (vmax - vmin) or 1.0
    pad_l, pad_r, pad_t, pad_b = 36, 12, 12, 28
    w, h = width - pad_l - pad_r, height - pad_t - pad_b
    n = len(vals)
    step = w / max(n - 1, 1)
    pts = []
    for idx, v in enumerate(vals):
        x = pad_l + idx * step
        y = pad_t + h - ((v - vmin) / span) * h
        pts.append((x, y))
    poly = " ".join(f"{x:.1f},{y:.1f}" for x, y in pts)
    area_poly = (
        f"{pts[0][0]:.1f},{pad_t + h:.1f} "
        + poly
        + f" {pts[-1][0]:.1f},{pad_t + h:.1f}"
    )
    # Y-Achse: min/max Label
    y_label_max = f"{vmax:,.0f}".replace(",", ".")
    y_label_min = f"{vmin:,.0f}".replace(",", ".")
    # X-Achse: first/mid/last Label
    def _x_label(i):
        return (
            str(items[i].get("label", "") or "")[:10]
        )
    x_first = _x_label(0)
    x_mid   = _x_label(n // 2)
    x_last  = _x_label(n - 1)
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 {width} {height}" '
        f'style="max-width:{width}px;font-family:-apple-system,Segoe UI,Roboto,sans-serif;">'
        f'<rect x="{pad_l}" y="{pad_t}" width="{w}" height="{h}" fill="#fafafa" stroke="#e0e0e0"/>'
        # horizontal gridlines (0.25 / 0.5 / 0.75)
        f'<line x1="{pad_l}" y1="{pad_t + h*0.25:.1f}" x2="{pad_l+w}" y2="{pad_t + h*0.25:.1f}" stroke="#eee"/>'
        f'<line x1="{pad_l}" y1="{pad_t + h*0.50:.1f}" x2="{pad_l+w}" y2="{pad_t + h*0.50:.1f}" stroke="#eee"/>'
        f'<line x1="{pad_l}" y1="{pad_t + h*0.75:.1f}" x2="{pad_l+w}" y2="{pad_t + h*0.75:.1f}" stroke="#eee"/>'
        f'<polygon points="{area_poly}" fill="{fill}" stroke="none"/>'
        f'<polyline points="{poly}" fill="none" stroke="{color}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"/>'
    )
    # Datenpunkte
    for x, y in pts:
        svg += f'<circle cx="{x:.1f}" cy="{y:.1f}" r="2.5" fill="{color}"/>'
    # Y-Achsenbeschriftung
    svg += (
        f'<text x="{pad_l - 4}" y="{pad_t + 10}" font-size="10" fill="#666" text-anchor="end">{y_label_max}</text>'
        f'<text x="{pad_l - 4}" y="{pad_t + h}" font-size="10" fill="#666" text-anchor="end">{y_label_min}</text>'
    )
    # X-Achsenbeschriftung
    svg += (
        f'<text x="{pad_l}" y="{height - 8}" font-size="10" fill="#666" text-anchor="start">{x_first}</text>'
        f'<text x="{pad_l + w/2:.1f}" y="{height - 8}" font-size="10" fill="#666" text-anchor="middle">{x_mid}</text>'
        f'<text x="{pad_l + w}" y="{height - 8}" font-size="10" fill="#666" text-anchor="end">{x_last}</text>'
    )
    svg += "</svg>"
    return {"type": "svg", "variant": "line", "title": title, "svg": svg}


def _build_chart_svg_heatmap(
    items: list[dict],
    title: str,
    rows: Optional[list[str]] = None,
    cols: Optional[list[str]] = None,
    cell: int = 28,
    color_base: str = "#1976d2",
) -> dict:
    """
    Inline-SVG 2D-Heatmap.
    items: [{"row": str|int, "col": str|int, "raw": float}, ...]
    rows / cols: optional explizite Achsenreihenfolge.
    """
    if not items:
        return {}
    rs = rows or sorted({str(i.get("row", "")) for i in items})
    cs = cols or sorted({str(i.get("col", "")) for i in items})
    vmax = max((float(i.get("raw") or 0) for i in items), default=0) or 1.0
    grid = {(str(i.get("row", "")), str(i.get("col", ""))): float(i.get("raw") or 0) for i in items}
    pad_l, pad_t, pad_r, pad_b = 80, 24, 12, 20
    w = pad_l + len(cs) * cell + pad_r
    h = pad_t + len(rs) * cell + pad_b
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 {w} {h}" '
        f'style="max-width:{w}px;font-family:-apple-system,Segoe UI,Roboto,sans-serif;">'
    )
    # Spaltenbeschriftung (oben)
    for ci, c in enumerate(cs):
        cx = pad_l + ci * cell + cell / 2
        svg += f'<text x="{cx:.1f}" y="{pad_t - 6}" font-size="10" fill="#666" text-anchor="middle">{c}</text>'
    # Zeilenbeschriftung (links) + Zellen
    for ri, r in enumerate(rs):
        ry = pad_t + ri * cell + cell / 2 + 4
        svg += f'<text x="{pad_l - 6}" y="{ry:.1f}" font-size="10" fill="#666" text-anchor="end">{r}</text>'
        for ci, c in enumerate(cs):
            v = grid.get((r, c), 0.0)
            opacity = min(1.0, v / vmax)
            x = pad_l + ci * cell
            y = pad_t + ri * cell
            svg += (
                f'<rect x="{x}" y="{y}" width="{cell-1}" height="{cell-1}" '
                f'fill="{color_base}" fill-opacity="{opacity:.2f}" stroke="#fff" stroke-width="1"/>'
            )
            if v >= vmax * 0.4:
                label_color = "#fff" if opacity > 0.6 else "#333"
                svg += (
                    f'<text x="{x + cell/2 - 0.5:.1f}" y="{y + cell/2 + 3.5:.1f}" '
                    f'font-size="9" fill="{label_color}" text-anchor="middle">{int(v)}</text>'
                )
    svg += "</svg>"
    return {"type": "svg", "variant": "heatmap", "title": title, "svg": svg}


def _build_chart_svg_donut(
    items: list[dict],
    title: str,
    size: int = 200,
    palette: Optional[list[str]] = None,
) -> dict:
    """
    Inline-SVG Donut-Chart für Proportionen.
    items: [{"label", "display", "raw"}, ...]
    """
    items = [i for i in items if (i.get("raw") or 0) > 0]
    if not items:
        return {}
    total = sum(float(i.get("raw") or 0) for i in items) or 1.0
    palette = palette or [
        "#1976d2", "#f57c00", "#388e3c", "#7b1fa2",
        "#c62828", "#00796b", "#fbc02d", "#5d4037",
    ]
    cx = cy = size / 2
    r_out = size / 2 - 6
    r_in  = r_out * 0.58
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" viewBox="0 0 {size} {size}" '
        f'style="font-family:-apple-system,Segoe UI,Roboto,sans-serif;">'
    )
    import math as _m
    angle = -_m.pi / 2  # start oben
    for idx, item in enumerate(items):
        frac = float(item.get("raw") or 0) / total
        if frac <= 0:
            continue
        a0 = angle
        a1 = angle + frac * 2 * _m.pi
        angle = a1
        large = 1 if frac > 0.5 else 0
        x0o = cx + r_out * _m.cos(a0); y0o = cy + r_out * _m.sin(a0)
        x1o = cx + r_out * _m.cos(a1); y1o = cy + r_out * _m.sin(a1)
        x0i = cx + r_in  * _m.cos(a1); y0i = cy + r_in  * _m.sin(a1)
        x1i = cx + r_in  * _m.cos(a0); y1i = cy + r_in  * _m.sin(a0)
        color = palette[idx % len(palette)]
        d = (
            f"M {x0o:.1f} {y0o:.1f} "
            f"A {r_out} {r_out} 0 {large} 1 {x1o:.1f} {y1o:.1f} "
            f"L {x0i:.1f} {y0i:.1f} "
            f"A {r_in} {r_in} 0 {large} 0 {x1i:.1f} {y1i:.1f} Z"
        )
        svg += f'<path d="{d}" fill="{color}" stroke="#fff" stroke-width="1"/>'
    # Zentrumstext: Summe
    svg += (
        f'<text x="{cx}" y="{cy - 2}" font-size="13" fill="#666" text-anchor="middle">Σ</text>'
        f'<text x="{cx}" y="{cy + 14}" font-size="14" font-weight="600" fill="#333" text-anchor="middle">'
        f'{int(total):,}</text>'.replace(",", ".")
    )
    svg += "</svg>"
    # Legende als HTML-nachbearbeitbare Struktur
    legend = [
        {
            "label": str(i.get("label", "")),
            "value": str(i.get("display", "")),
            "color": palette[idx % len(palette)],
            "pct":   round(float(i.get("raw") or 0) / total * 100, 1),
        }
        for idx, i in enumerate(items)
    ]
    return {"type": "svg", "variant": "donut", "title": title, "svg": svg, "legend": legend}


def _build_chart_svg_sparkline(
    values: list[float] | list[dict],
    width: int = 100,
    height: int = 24,
    color: str = "#1976d2",
) -> dict:
    """
    Winziger Trend-Sparkline für KPI-Karten.
    values: Liste von floats oder dicts mit 'raw'-Schlüssel.
    """
    raw = []
    for v in values or []:
        if isinstance(v, dict):
            raw.append(float(v.get("raw") or 0))
        else:
            raw.append(float(v or 0))
    if len(raw) < 2:
        return {}
    vmax = max(raw); vmin = min(raw)
    span = (vmax - vmin) or 1.0
    n = len(raw)
    step = (width - 4) / max(n - 1, 1)
    pts = []
    for idx, v in enumerate(raw):
        x = 2 + idx * step
        y = 2 + (height - 4) - ((v - vmin) / span) * (height - 4)
        pts.append(f"{x:.1f},{y:.1f}")
    pl = " ".join(pts)
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" '
        f'style="display:inline-block;vertical-align:middle;">'
        f'<polyline points="{pl}" fill="none" stroke="{color}" stroke-width="1.5" '
        f'stroke-linejoin="round" stroke-linecap="round"/>'
        f"</svg>"
    )
    return {"type": "svg", "variant": "sparkline", "svg": svg}


# ─── Report-Generatoren ───────────────────────────────────────────────────────

def build_print_stats_report(
    rows: list[dict],
    period: str,
    layout: Optional[dict] = None,
    group_by: str = "day",
    labels: Optional[dict] = None,
) -> dict[str, Any]:
    """Baut die Report-Datenstruktur für print_stats-Ergebnisse (i18n-aware)."""
    layout = layout or {}
    totals = {
        "total_jobs":   sum(r.get("total_jobs", 0) or 0 for r in rows),
        "total_pages":  sum(r.get("total_pages", 0) or 0 for r in rows),
        "color_pages":  sum(r.get("color_pages", 0) or 0 for r in rows),
        "bw_pages":     sum(r.get("bw_pages", 0) or 0 for r in rows),
        "duplex_pages": sum(r.get("duplex_pages", 0) or 0 for r in rows),
        "saved_sheets": sum(r.get("saved_sheets_duplex", 0) or 0 for r in rows),
    }
    color_pct  = totals["color_pages"] / max(totals["total_pages"], 1) * 100
    duplex_pct = totals["duplex_pages"] / max(totals["total_pages"], 1) * 100

    col_label_map = {
        "day":     _lbl(labels, "rpt_eng_col_date"),
        "week":    _lbl(labels, "rpt_eng_col_week"),
        "month":   _lbl(labels, "rpt_eng_col_month"),
        "user":    _lbl(labels, "rpt_eng_col_user"),
        "printer": _lbl(labels, "rpt_eng_col_printer"),
        "site":    _lbl(labels, "rpt_eng_col_site"),
    }
    col_label = col_label_map.get(group_by, _lbl(labels, "rpt_eng_col_period"))
    is_date_group = group_by in ("day", "week", "month")

    def _fmt_period(val: Any) -> str:
        s = str(val if val is not None else "")
        return s.split("T")[0] if is_date_group else s

    # v3.8.1: Sparklines für KPI-Karten (Zeitreihe → winzige Trendkurve)
    _spark_series = (
        [r.get("total_pages", 0) or 0 for r in rows] if is_date_group else []
    )
    _spark_color = _build_chart_svg_sparkline(
        [r.get("color_pages", 0) or 0 for r in rows], color="#f57c00"
    ) if is_date_group else {}
    _spark_bw = _build_chart_svg_sparkline(
        [r.get("bw_pages", 0) or 0 for r in rows], color="#616161"
    ) if is_date_group else {}
    _spark_total = _build_chart_svg_sparkline(
        _spark_series, color=layout.get("primary_color", "#1976d2")
    ) if is_date_group else {}
    _spark_duplex = _build_chart_svg_sparkline(
        [r.get("duplex_pct", 0) or 0 for r in rows], color="#388e3c"
    ) if is_date_group else {}

    kpis = [
        {"label": _lbl(labels, "rpt_eng_kpi_total_pages"),
         "value": _fmt_num(totals["total_pages"]),
         "sub":   f"{_fmt_num(totals['total_jobs'])} {_lbl(labels, 'rpt_eng_col_jobs')}",
         "sparkline": _spark_total},
        {"label": _lbl(labels, "rpt_eng_kpi_color_pages"),
         "value": _fmt_num(totals["color_pages"]),
         "sub":   _fmt_pct(color_pct),
         "sparkline": _spark_color},
        {"label": _lbl(labels, "rpt_eng_kpi_bw_pages"),
         "value": _fmt_num(totals["bw_pages"]),
         "sub":   _fmt_pct(100 - color_pct),
         "sparkline": _spark_bw},
        {"label": _lbl(labels, "rpt_eng_kpi_duplex_pct"),
         "value": _fmt_pct(duplex_pct),
         "sub":   f"{_fmt_num(totals['saved_sheets'])} {_lbl(labels, 'rpt_eng_kpi_saved_sheets')}",
         "sparkline": _spark_duplex},
    ]

    table_cols = [
        col_label,
        _lbl(labels, "rpt_eng_col_jobs"),
        _lbl(labels, "rpt_eng_col_pages"),
        _lbl(labels, "rpt_eng_col_color"),
        _lbl(labels, "rpt_eng_col_bw"),
        _lbl(labels, "rpt_eng_col_color_pct"),
        _lbl(labels, "rpt_eng_col_duplex_pct"),
    ]
    table_rows = []
    for r in rows:
        table_rows.append([
            _fmt_period(r.get("period", "")),
            _fmt_num(r.get("total_jobs")),
            _fmt_num(r.get("total_pages")),
            _fmt_num(r.get("color_pages")),
            _fmt_num(r.get("bw_pages")),
            _fmt_pct(r.get("color_pct")),
            _fmt_pct(r.get("duplex_pct")),
        ])

    # v3.8.1: bei Datumsgruppierung SVG-Liniendiagramm, sonst Balken.
    _chart_label_len = 10 if is_date_group else 24
    chart_items = [
        {"label": _fmt_period(r.get("period", ""))[:_chart_label_len],
         "display": _fmt_num(r.get("total_pages")),
         "raw": r.get("total_pages", 0) or 0}
        for r in rows
    ]
    chart_title = f"{_lbl(labels, 'rpt_eng_col_pages')} — {col_label}"
    if is_date_group and len(chart_items) >= 2:
        chart = _build_chart(
            chart_items, chart_title, chart_type="line",
            color=layout.get("primary_color", "#1976d2"),
        )
    else:
        chart = _build_chart(chart_items, chart_title)

    sections = [{"title": _lbl(labels, "rpt_eng_section_details"),
                 "columns": table_cols,
                 "rows": table_rows,
                 "chart": chart}]

    # v3.8.1: Zusatz-Donut S/W vs Farbe
    if totals["total_pages"] > 0:
        donut = _build_chart(
            [
                {"label": _lbl(labels, "rpt_eng_col_color"),
                 "display": _fmt_num(totals["color_pages"]),
                 "raw": totals["color_pages"] or 0},
                {"label": _lbl(labels, "rpt_eng_col_bw"),
                 "display": _fmt_num(totals["bw_pages"]),
                 "raw": totals["bw_pages"] or 0},
            ],
            _lbl(labels, "rpt_eng_chart_color_vs_bw"),
            chart_type="donut",
            palette=["#f57c00", "#616161"],
        )
        if donut:
            sections.append({
                "title": _lbl(labels, "rpt_eng_chart_color_vs_bw"),
                "columns": [], "rows": [], "chart": donut,
            })

    return {
        "kpis": kpis,
        "sections": sections,
        "_totals": totals,
    }


def build_cost_report_report(
    rows: list[dict],
    period: str,
    layout: Optional[dict] = None,
    currency: str = "€",
    group_by: str = "day",
    labels: Optional[dict] = None,
) -> dict[str, Any]:
    """Baut die Report-Datenstruktur für cost_report-Ergebnisse (i18n-aware).

    group_by bestimmt, wie die erste Spalte ("period") beschriftet wird —
    je nach SQL-Gruppierung kann das ein Datum, ein Benutzer, ein Drucker
    oder ein Standort sein. Ohne diese Information stand früher immer
    "Datum" in der Kopfzeile, auch wenn die Werte E-Mails waren.
    """
    totals = {k: sum(r.get(k, 0) or 0 for r in rows)
              for k in ("total_pages", "color_pages", "bw_pages", "toner_cost_color",
                        "toner_cost_bw", "sheet_cost", "total_cost")}

    col_label_map = {
        "day":     _lbl(labels, "rpt_eng_col_date"),
        "week":    _lbl(labels, "rpt_eng_col_week"),
        "month":   _lbl(labels, "rpt_eng_col_month"),
        "user":    _lbl(labels, "rpt_eng_col_user"),
        "printer": _lbl(labels, "rpt_eng_col_printer"),
        "site":    _lbl(labels, "rpt_eng_col_site"),
    }
    period_col_label = col_label_map.get(group_by, _lbl(labels, "rpt_eng_col_period"))
    # Datum/Woche/Monat → 'YYYY-MM-DD'-Truncation; Text-Werte (User/Printer/Site)
    # bleiben unverändert.
    is_date_group = group_by in ("day", "week", "month")

    kpis = [
        {"label": _lbl(labels, "rpt_eng_kpi_total_cost"),
         "value": _fmt_cost(totals["total_cost"], currency),
         "sub":   None},
        {"label": _lbl(labels, "rpt_eng_kpi_toner_color"),
         "value": _fmt_cost(totals["toner_cost_color"], currency),
         "sub":   f"{_fmt_num(totals['color_pages'])} {_lbl(labels, 'rpt_eng_col_color')}"},
        {"label": _lbl(labels, "rpt_eng_kpi_toner_bw"),
         "value": _fmt_cost(totals["toner_cost_bw"], currency),
         "sub":   f"{_fmt_num(totals['bw_pages'])} {_lbl(labels, 'rpt_eng_col_bw')}"},
        {"label": _lbl(labels, "rpt_eng_kpi_paper"),
         "value": _fmt_cost(totals["sheet_cost"], currency),
         "sub":   f"{_fmt_num(totals['total_pages'])} {_lbl(labels, 'rpt_eng_col_pages')}"},
    ]

    table_cols = [
        period_col_label,
        _lbl(labels, "rpt_eng_col_pages"),
        _lbl(labels, "rpt_eng_col_color"),
        _lbl(labels, "rpt_eng_col_bw"),
        _lbl(labels, "rpt_eng_col_toner_color"),
        _lbl(labels, "rpt_eng_col_toner_bw"),
        _lbl(labels, "rpt_eng_col_paper"),
        _lbl(labels, "rpt_eng_col_total"),
    ]

    def _fmt_period(val: Any) -> str:
        s = str(val if val is not None else "")
        return s.split("T")[0] if is_date_group else s

    table_rows = []
    for r in rows:
        table_rows.append([
            _fmt_period(r.get("period", "")),
            _fmt_num(r.get("total_pages")),
            _fmt_num(r.get("color_pages")),
            _fmt_num(r.get("bw_pages")),
            _fmt_cost(r.get("toner_cost_color"), currency),
            _fmt_cost(r.get("toner_cost_bw"), currency),
            _fmt_cost(r.get("sheet_cost"), currency),
            _fmt_cost(r.get("total_cost"), currency),
        ])

    cost_items = [
        {"label": _fmt_period(r.get("period", ""))[:20],
         "display": _fmt_cost(r.get("total_cost"), currency),
         "raw": float(r.get("total_cost", 0) or 0)}
        for r in rows
    ]
    cost_title = f"{_lbl(labels, 'rpt_eng_col_cost')} — {period_col_label} ({currency})"
    if is_date_group and len(cost_items) >= 2:
        chart = _build_chart(
            cost_items, cost_title, chart_type="line",
            color=(layout or {}).get("primary_color", "#1976d2"),
        )
    else:
        chart = _build_chart(cost_items, cost_title)
    return {
        "kpis": kpis,
        "sections": [{"title": _lbl(labels, "rpt_eng_section_details"),
                      "columns": table_cols,
                      "rows": table_rows,
                      "chart": chart}],
        "_totals": totals,
    }


def build_top_users_report(
    rows: list[dict],
    period: str,
    currency: str = "€",
    labels: Optional[dict] = None,
) -> dict[str, Any]:
    """Baut die Report-Datenstruktur für top_users-Ergebnisse (i18n-aware)."""
    table_cols = [
        "#",
        _lbl(labels, "rpt_eng_col_user"),
        _lbl(labels, "rpt_eng_col_dept"),
        _lbl(labels, "rpt_eng_col_jobs"),
        _lbl(labels, "rpt_eng_col_pages"),
        _lbl(labels, "rpt_eng_col_color"),
        _lbl(labels, "rpt_eng_col_color_pct"),
        _lbl(labels, "rpt_eng_col_cost"),
    ]
    table_rows = []
    for i, r in enumerate(rows, 1):
        table_rows.append([
            str(i),
            r.get("email", "—"),
            r.get("department") or "—",
            _fmt_num(r.get("total_jobs")),
            _fmt_num(r.get("total_pages")),
            _fmt_num(r.get("color_pages")),
            _fmt_pct(r.get("color_pct")),
            _fmt_cost(r.get("total_cost"), currency),
        ])
    kpis = []
    if rows:
        kpis = [
            {"label": _lbl(labels, "rpt_eng_kpi_active_users"),
             "value": str(len(rows)),
             "sub":   None},
            {"label": _lbl(labels, "rpt_eng_kpi_most_pages"),
             "value": rows[0].get("email", "—"),
             "sub":   _fmt_num(rows[0].get("total_pages"))},
        ]
    chart = _build_chart(
        [{"label": r.get("email", "—").split("@")[0][:20],
          "display": _fmt_num(r.get("total_pages")),
          "raw": r.get("total_pages", 0) or 0}
         for r in rows],
        _lbl(labels, "rpt_eng_section_top_users"),
        max_items=15,
    )
    return {
        "kpis": kpis,
        "sections": [{"title": _lbl(labels, "rpt_eng_section_top_users"),
                      "columns": table_cols,
                      "rows": table_rows,
                      "chart": chart}],
    }


def build_top_printers_report(
    rows: list[dict],
    period: str,
    currency: str = "€",
    labels: Optional[dict] = None,
) -> dict[str, Any]:
    """Baut die Report-Datenstruktur für top_printers-Ergebnisse (i18n-aware)."""
    table_cols = [
        "#",
        _lbl(labels, "rpt_eng_col_printer"),
        _lbl(labels, "rpt_eng_col_model"),
        _lbl(labels, "rpt_eng_col_location"),
        _lbl(labels, "rpt_eng_col_site"),
        _lbl(labels, "rpt_eng_col_jobs"),
        _lbl(labels, "rpt_eng_col_pages"),
        _lbl(labels, "rpt_eng_col_color_pct"),
        _lbl(labels, "rpt_eng_col_cost"),
    ]
    table_rows = []
    for i, r in enumerate(rows, 1):
        table_rows.append([
            str(i),
            r.get("printer_name", "—"),
            r.get("model_name") or "—",
            r.get("location") or "—",
            r.get("site_name") or "—",
            _fmt_num(r.get("total_jobs")),
            _fmt_num(r.get("total_pages")),
            _fmt_pct(r.get("color_pct")),
            _fmt_cost(r.get("total_cost"), currency),
        ])
    chart = _build_chart(
        [{"label": r.get("printer_name", "—")[:20],
          "display": _fmt_num(r.get("total_pages")),
          "raw": r.get("total_pages", 0) or 0}
         for r in rows],
        _lbl(labels, "rpt_eng_section_top_printers"),
        max_items=15,
    )
    return {
        "kpis": [],
        "sections": [{"title": _lbl(labels, "rpt_eng_section_top_printers"),
                      "columns": table_cols,
                      "rows": table_rows,
                      "chart": chart}],
    }


def build_trend_report(
    trend: dict,
    currency: str = "€",
    labels: Optional[dict] = None,
) -> dict[str, Any]:
    """Baut die Report-Datenstruktur für trend-Ergebnisse (i18n-aware)."""
    p1, p2, delta = trend.get("period1", {}), trend.get("period2", {}), trend.get("delta", {})

    table_cols = [
        _lbl(labels, "rpt_eng_col_metric"),
        _lbl(labels, "rpt_eng_col_p1"),
        _lbl(labels, "rpt_eng_col_p2"),
        _lbl(labels, "rpt_eng_col_delta"),
    ]
    metrics = [
        (_lbl(labels, "rpt_eng_kpi_total_pages"), "total_pages",  _fmt_num),
        (_lbl(labels, "rpt_eng_kpi_color_pages"), "color_pages",  _fmt_num),
        (_lbl(labels, "rpt_eng_kpi_bw_pages"),    "bw_pages",     _fmt_num),
        (_lbl(labels, "rpt_eng_kpi_total_jobs"),  "total_jobs",   _fmt_num),
        (_lbl(labels, "rpt_eng_kpi_active_users"),"active_users", _fmt_num),
        (_lbl(labels, "rpt_eng_kpi_total_cost"),  "total_cost",   lambda v: _fmt_cost(v, currency)),
    ]
    table_rows = []
    for label, key, fmt in metrics:
        table_rows.append([
            label,
            fmt(p1.get(key)),
            fmt(p2.get(key)),
            _fmt_delta(delta.get(key)),
        ])

    p1_range = f"{p1.get('start','?')} – {p1.get('end','?')}"
    p2_range = f"{p2.get('start','?')} – {p2.get('end','?')}"
    vs_prev  = _lbl(labels, "rpt_eng_vs_prev")

    return {
        "kpis": [
            {"label": f"{_lbl(labels, 'rpt_eng_kpi_total_pages')} ({_lbl(labels, 'rpt_eng_col_p1')})",
             "value": _fmt_num(p1.get("total_pages")), "sub": p1_range},
            {"label": f"{_lbl(labels, 'rpt_eng_kpi_total_pages')} ({_lbl(labels, 'rpt_eng_col_p2')})",
             "value": _fmt_num(p2.get("total_pages")), "sub": p2_range},
            {"label": f"Δ {_lbl(labels, 'rpt_eng_kpi_total_pages')}",
             "value": f"{delta.get('total_pages', '—')} %", "sub": vs_prev},
            {"label": f"Δ {_lbl(labels, 'rpt_eng_kpi_total_cost')}",
             "value": f"{delta.get('total_cost', '—')} %",  "sub": vs_prev},
        ],
        "sections": [{"title": _lbl(labels, "rpt_eng_section_trend"),
                      "columns": table_cols,
                      "rows": table_rows}],
    }


# ─── Hour × Weekday Heatmap Report (v3.8.1) ──────────────────────────────────

def build_hour_dow_heatmap_report(
    rows: list[dict],
    period: str,
    layout: Optional[dict] = None,
    labels: Optional[dict] = None,
) -> dict[str, Any]:
    """
    Baut die Report-Datenstruktur für die Nutzungs-Heatmap (v3.8.1).
    Erwartet flache Rows aus query_hour_dow_heatmap: {hour, dow, total_pages, total_jobs}.
    """
    rows = rows or []
    layout = layout or {}

    # Aggregierte KPIs
    total_pages = sum(int(r.get("total_pages") or 0) for r in rows)
    total_jobs  = sum(int(r.get("total_jobs")  or 0) for r in rows)

    # Peak-Zelle ermitteln
    peak = None
    for r in rows:
        if peak is None or (int(r.get("total_pages") or 0) > int(peak.get("total_pages") or 0)):
            peak = r

    # Wochentagslabels ISO: 1=Sonntag..7=Samstag (SQL DATEFIRST 7).
    # Wir stellen die Zeilen in bekannter Lesereihenfolge Mo..So dar.
    dow_keys_order = [2, 3, 4, 5, 6, 7, 1]  # Mo, Di, Mi, Do, Fr, Sa, So
    dow_label_keys = {
        1: "rpt_eng_dow_sun",
        2: "rpt_eng_dow_mon",
        3: "rpt_eng_dow_tue",
        4: "rpt_eng_dow_wed",
        5: "rpt_eng_dow_thu",
        6: "rpt_eng_dow_fri",
        7: "rpt_eng_dow_sat",
    }
    row_labels = [_lbl(labels, dow_label_keys[k]) for k in dow_keys_order]
    col_labels = [f"{h:02d}" for h in range(24)]

    # Heatmap-Items: row=DOW-Label, col=Stunde, raw=total_pages
    items = []
    key_to_label = {k: _lbl(labels, dow_label_keys[k]) for k in dow_keys_order}
    for r in rows:
        dow = int(r.get("dow") or 0)
        hour = int(r.get("hour") or 0)
        if dow not in key_to_label:
            continue
        items.append({
            "row": key_to_label[dow],
            "col": f"{hour:02d}",
            "raw": float(r.get("total_pages") or 0),
        })

    heatmap = _build_chart(
        items,
        _lbl(labels, "rpt_eng_chart_hour_dow"),
        chart_type="heatmap",
        rows=row_labels,
        cols=col_labels,
        color_base=layout.get("primary_color", "#1976d2"),
        cell=24,
    )

    peak_hint = ""
    if peak and (peak.get("total_pages") or 0) > 0:
        peak_dow_label = key_to_label.get(int(peak.get("dow") or 0), "?")
        peak_hint = f"{peak_dow_label} {int(peak.get('hour') or 0):02d}:00"

    kpis = [
        {
            "label": _lbl(labels, "rpt_eng_kpi_total_pages"),
            "value": _fmt_num(total_pages),
            "sub": period,
        },
        {
            "label": _lbl(labels, "rpt_eng_kpi_total_jobs"),
            "value": _fmt_num(total_jobs),
            "sub": period,
        },
        {
            "label": _lbl(labels, "rpt_eng_kpi_peak_slot"),
            "value": peak_hint or "—",
            "sub": _fmt_num((peak or {}).get("total_pages") or 0),
        },
    ]

    sections = []
    if heatmap:
        sections.append({
            "title": _lbl(labels, "rpt_eng_chart_hour_dow"),
            "columns": [],
            "rows": [],
            "chart": heatmap,
        })

    # Optional: Top-5-Slots als Tabelle
    top5 = sorted(rows, key=lambda r: int(r.get("total_pages") or 0), reverse=True)[:5]
    if top5:
        t_rows = []
        for r in top5:
            dow = int(r.get("dow") or 0)
            t_rows.append([
                key_to_label.get(dow, "?"),
                f"{int(r.get('hour') or 0):02d}:00",
                _fmt_num(r.get("total_pages")),
                _fmt_num(r.get("total_jobs")),
            ])
        sections.append({
            "title": _lbl(labels, "rpt_eng_section_top_slots"),
            "columns": [
                _lbl(labels, "rpt_eng_col_weekday"),
                _lbl(labels, "rpt_eng_col_hour"),
                _lbl(labels, "rpt_eng_kpi_total_pages"),
                _lbl(labels, "rpt_eng_kpi_total_jobs"),
            ],
            "rows": t_rows,
        })

    return {"kpis": kpis, "sections": sections}


# ─── Ausgabe-Renderer ─────────────────────────────────────────────────────────

def _derive_density(density: str) -> tuple[int, int, int]:
    """Liefert (content_padding, section_gap, table_cell_py) für eine Density-Stufe."""
    return {
        "compact": (18, 14, 5),
        "normal":  (26, 22, 8),
        "airy":    (36, 32, 12),
    }.get(density, (26, 22, 8))


def _derive_logo_src(layout: dict) -> str:
    """
    Baut den Logo-src-Wert:
      - wenn layout.logo_base64 vorhanden → data-URI
      - sonst wenn layout.logo_url vorhanden → URL (legacy)
      - sonst ""
    """
    b64 = (layout.get("logo_base64") or "").strip()
    if b64:
        mime = layout.get("logo_mime", "image/png")
        # Wenn schon data-URI, nicht nochmal wrappen
        if b64.startswith("data:"):
            return b64
        return f"data:{mime};base64,{b64}"
    url = (layout.get("logo_url") or "").strip()
    return url


def render_html(
    title: str,
    period: str,
    report_data: dict[str, Any],
    layout: Optional[dict] = None,
    labels: Optional[dict] = None,
    lang: str = "en",
) -> str:
    """Rendert den Report als vollständige HTML-Seite (i18n + theme-aware)."""
    if not JINJA2_AVAILABLE:
        return _plain_html_fallback(title, period, report_data, layout)

    # Layout normalisieren (Defaults, Theme-Farben, Migration)
    layout = normalize_layout(layout or {})

    # Typography
    font_key  = layout.get("font_family", "arial")
    font_css  = FONTS_BY_KEY.get(font_key, FONTS_BY_KEY["arial"])["css"]

    # Density → CSS-Werte
    d_pad, d_gap, d_cell = _derive_density(layout.get("density", "normal"))

    # v3.9.2 — autoescape=True. Tabellenzellen werden damit automatisch
    # HTML-escaped (vorher konnte ein Dateiname wie '<img src=x onerror=…>'
    # in einem HTML-Report Skripte ausführen). SVG-Charts werden weiterhin
    # mit '| safe' gerendert, weil sie engine-intern erzeugt werden und
    # vertrauenswürdig sind.
    env = Environment(loader=BaseLoader(), autoescape=True)
    template = env.from_string(_HTML_TEMPLATE)
    return template.render(
        # i18n
        lang=lang,
        title=title,
        period=period,
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
        period_label=_lbl(labels, "rpt_eng_period"),
        generated_label=_lbl(labels, "rpt_eng_generated_at"),
        no_data_label=_lbl(labels, "rpt_eng_no_data"),
        footer_default=_lbl(labels, "rpt_eng_footer_default"),

        # Branding
        company_name=layout.get("company_name", ""),
        footer_text=layout.get("footer_text", ""),
        logo_src=_derive_logo_src(layout),

        # Theme colors
        primary_color=layout.get("primary_color"),
        accent_color=layout.get("accent_color"),
        background_color=layout.get("background_color"),
        text_color=layout.get("text_color"),
        muted_color=layout.get("muted_color"),
        table_header_bg=layout.get("table_header_bg"),
        table_alt_bg=layout.get("table_alt_bg"),

        # Typography
        font_css=font_css,
        font_size_base=layout.get("font_size_base", 13),
        font_size_h1=layout.get("font_size_h1", 22),
        font_size_h2=layout.get("font_size_h2", 15),

        # Layout
        header_variant=layout.get("header_variant", "left"),
        density_padding=d_pad,
        density_gap=d_gap,
        density_cell_py=d_cell,

        # Charts
        charts_enabled=layout.get("charts_enabled", True),
        chart_style=layout.get("chart_style", "bars"),

        # Data
        kpis=report_data.get("kpis", []),
        sections=report_data.get("sections", []),
    )


def _plain_html_fallback(title, period, report_data, layout) -> str:
    """v3.9.2 — alle dynamischen Werte werden über html.escape() geführt,
    damit ein Dateiname/Username mit '<' oder Anführungszeichen den
    Plain-HTML-Fallback nicht in einen XSS-Vektor verwandelt."""
    import html as _h
    e = lambda v: _h.escape("" if v is None else str(v), quote=True)
    def _safe_cell(cell):
        """Delta-Markup durchlassen, alles andere escapen."""
        s = "" if cell is None else str(cell)
        if '<span class="delta-' in s:
            return s
        return _h.escape(s, quote=True)
    lines = [f"<html><body><h1>{e(title)}</h1><p>{e(period)}</p>"]
    for section in report_data.get("sections", []):
        lines.append(f"<h2>{e(section.get('title', ''))}</h2><table border='1'>")
        lines.append("<tr>" + "".join(f"<th>{e(c)}</th>" for c in section.get("columns", [])) + "</tr>")
        for row in section.get("rows", []):
            lines.append("<tr>" + "".join(f"<td>{_safe_cell(cell)}</td>" for cell in row) + "</tr>")
        lines.append("</table>")
    lines.append("</body></html>")
    return "\n".join(lines)


def render_csv(rows: list[dict]) -> str:
    """Rendert rohe Query-Ergebnisse als CSV."""
    if not rows:
        return ""
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=list(rows[0].keys()), extrasaction="ignore")
    writer.writeheader()
    for row in rows:
        writer.writerow({k: str(v) if v is not None else "" for k, v in row.items()})
    return output.getvalue()


def render_json(data: Any) -> str:
    """Serialisiert Daten als formatiertes JSON."""
    return json.dumps(data, indent=2, ensure_ascii=False, default=str)


def _strip_delta_html(text: str) -> str:
    """Entfernt die <span class="delta-*">…</span> HTML-Markierung für PDF/XLSX."""
    import re
    # <span class="delta-pos">▲ 12.3%</span>  →  ▲ 12.3%
    return re.sub(r'<[^>]+>', '', str(text))


def render_pdf(
    title: str,
    period: str,
    report_data: dict,
    layout: Optional[dict] = None,
    labels: Optional[dict] = None,
) -> bytes:
    """
    Erzeugt einen PDF-Report aus den Report-Daten (i18n + theme-aware).

    Verwendet fpdf2 mit Helvetica/Courier/Times (Latin-1) — Font-Key aus
    layout.font_family wird auf eine fpdf2-Familie gemappt. Alle Nicht-
    Latin1-Zeichen werden durch _pdf_safe() ersetzt.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        logger.error("fpdf2 nicht installiert — PDF-Generierung nicht verfügbar")
        return b""

    layout = normalize_layout(layout or {})
    primary_color   = layout.get("primary_color", "#1a73e8")
    table_header_bg = layout.get("table_header_bg", primary_color)
    table_alt_hex   = layout.get("table_alt_bg", "#F9F9F9")

    # Font-Key → fpdf2 family
    font_key    = layout.get("font_family", "arial")
    font_family = FONTS_BY_KEY.get(font_key, FONTS_BY_KEY["arial"]).get("pdf_family", "Helvetica")

    # Hex → RGB
    def hex_to_rgb(h: str, fallback=(26, 115, 232)):
        try:
            h = (h or "").lstrip("#")
            if len(h) == 3:
                h = "".join(c * 2 for c in h)
            return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))
        except Exception:
            return fallback

    r, g, b       = hex_to_rgb(primary_color)
    thr, thg, thb = hex_to_rgb(table_header_bg, (r, g, b))
    tar, tag, tab = hex_to_rgb(table_alt_hex, (249, 249, 249))

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # v3.7.9: Logo aus layout.logo_base64 einbetten (falls vorhanden).
    # Wird rechts oben in den farbigen Header gezeichnet, bevor der Text kommt.
    # fpdf2 akzeptiert BytesIO mit PNG/JPEG direkt (ab Version 2.5).
    logo_bytes = None
    try:
        b64 = (layout.get("logo_base64") or "").strip()
        if b64:
            if b64.startswith("data:"):
                # data:image/png;base64,<payload>
                _, _, _payload = b64.partition(",")
                b64 = _payload
            import base64 as _b64
            logo_bytes = _b64.b64decode(b64)
    except Exception as _e:
        logger.warning("Logo konnte nicht f\u00fcr PDF dekodiert werden: %s", _e)
        logo_bytes = None

    # Header-Hintergrund
    header_height = 19  # 12 (Titel) + 7 (Untertitel)
    pdf.set_fill_color(r, g, b)
    pdf.rect(0, pdf.get_y(), pdf.w, header_height, style="F")

    # Logo rechts oben im Header
    if logo_bytes:
        try:
            import io as _io
            logo_h = 14
            logo_w = 28   # max Breite, fpdf skaliert Aspect Ratio automatisch wenn h gesetzt
            logo_x = pdf.w - pdf.r_margin - logo_w
            logo_y = pdf.get_y() + (header_height - logo_h) / 2
            pdf.image(_io.BytesIO(logo_bytes), x=logo_x, y=logo_y, h=logo_h)
        except Exception as _e:
            logger.warning("Logo-Embedding im PDF fehlgeschlagen: %s", _e)

    # Header-Text
    pdf.set_text_color(255, 255, 255)
    pdf.set_font(font_family, "B", 16)
    pdf.cell(0, 12, _pdf_safe(title), ln=True, fill=False, align="L")
    pdf.set_font(font_family, "", 9)
    period_lbl    = _lbl(labels, "rpt_eng_period")
    generated_lbl = _lbl(labels, "rpt_eng_generated_at")
    pdf.cell(0, 7, _pdf_safe(f"{period_lbl}: {period}  |  {generated_lbl}: {datetime.now().strftime('%Y-%m-%d %H:%M')}"),
             ln=True, fill=False, align="L")
    pdf.ln(4)

    # KPIs
    kpis = report_data.get("kpis", [])
    if kpis:
        pdf.set_fill_color(240, 244, 255)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font(font_family, "B", 10)
        pdf.cell(0, 6, _pdf_safe(_lbl(labels, "rpt_eng_section_summary")), ln=True)
        pdf.ln(2)
        for kpi in kpis:
            pdf.set_font(font_family, "B", 11)
            pdf.set_text_color(r, g, b)
            pdf.cell(0, 7, _pdf_safe(f"  {kpi.get('label','')}: {kpi.get('value','')}"), ln=True, fill=True)
            if kpi.get("sub"):
                pdf.set_font(font_family, "", 9)
                pdf.set_text_color(120, 120, 120)
                pdf.cell(0, 5, _pdf_safe(f"    {kpi['sub']}"), ln=True)
        pdf.ln(4)

    # Sections / Tabellen
    pdf.set_text_color(0, 0, 0)
    for section in report_data.get("sections", []):
        pdf.set_font(font_family, "B", 12)
        pdf.set_text_color(r, g, b)
        pdf.cell(0, 8, _pdf_safe(section.get("title", "")), ln=True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(1)

        columns = section.get("columns", [])
        rows = section.get("rows", [])
        if not rows:
            pdf.set_font(font_family, "I", 9)
            pdf.set_text_color(150, 150, 150)
            pdf.cell(0, 6, _pdf_safe(_lbl(labels, "rpt_eng_no_data")), ln=True)
            pdf.ln(3)
            continue

        # Spaltenbreiten gleichmäßig verteilen
        page_w = pdf.w - 2 * pdf.l_margin
        col_w = page_w / max(len(columns), 1)

        # Tabellenkopf
        pdf.set_fill_color(thr, thg, thb)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font(font_family, "B", 8)
        for col in columns:
            pdf.cell(col_w, 7, _pdf_safe(str(col)), border=0, fill=True)
        pdf.ln()

        # Tabellenzeilen
        pdf.set_font(font_family, "", 8)
        for i, row in enumerate(rows):
            if i % 2 == 0:
                pdf.set_fill_color(tar, tag, tab)
            else:
                pdf.set_fill_color(255, 255, 255)
            pdf.set_text_color(0, 0, 0)
            for cell in row:
                # Delta-HTML aus trend-Report strippen
                text = _strip_delta_html(cell)
                pdf.cell(col_w, 6, _pdf_safe(str(text)), border=0, fill=True)
            pdf.ln()
        pdf.ln(4)

    return bytes(pdf.output())


def render_xlsx(
    title: str,
    period: str,
    report_data: dict,
    layout: Optional[dict] = None,
    labels: Optional[dict] = None,
) -> bytes:
    """
    Erzeugt einen Excel-Report (XLSX) aus den Report-Daten (i18n + theme-aware).
    Verwendet openpyxl.
    """
    try:
        import openpyxl
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    except ImportError:
        logger.error("openpyxl nicht installiert — XLSX-Generierung nicht verfügbar")
        return b""

    layout = normalize_layout(layout or {})

    def _hex(h: str, fallback: str) -> str:
        h = (h or "").lstrip("#")
        if len(h) == 3:
            h = "".join(c * 2 for c in h)
        if len(h) != 6:
            return fallback
        return h.upper()

    header_hex  = _hex(layout.get("table_header_bg"), "1A73E8")
    alt_hex     = _hex(layout.get("table_alt_bg"),    "F9F9F9")

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Report"

    header_fill = PatternFill("solid", fgColor=header_hex)
    header_font = Font(bold=True, color="FFFFFF", size=10)
    kpi_font    = Font(bold=True, size=11)
    thin_border = Border(bottom=Side(style="thin", color="DDDDDD"))

    # Logo einbetten (falls vorhanden) — oben rechts, Ankerzelle E1
    try:
        b64 = (layout.get("logo_base64") or "").strip()
        if b64:
            if b64.startswith("data:"):
                _, _, _payload = b64.partition(",")
                b64 = _payload
            import base64 as _b64
            logo_bytes = _b64.b64decode(b64)
            from openpyxl.drawing.image import Image as _XlImg
            _img = _XlImg(io.BytesIO(logo_bytes))
            # Hoehe auf ca. 50px begrenzen, Seitenverhaeltnis beibehalten
            try:
                if _img.height and _img.width:
                    _ratio = _img.width / float(_img.height)
                    _img.height = 50
                    _img.width  = int(50 * _ratio)
            except Exception:
                pass
            _img.anchor = "E1"
            ws.add_image(_img)
    except Exception as _e:
        logger.warning("Logo-Embedding im XLSX fehlgeschlagen: %s", _e)

    row_idx = 1

    # Titel
    ws.cell(row_idx, 1, title)
    ws.cell(row_idx, 1).font = Font(bold=True, size=14)
    row_idx += 1
    ws.cell(
        row_idx, 1,
        f"{_lbl(labels, 'rpt_eng_period')}: {period}  |  "
        f"{_lbl(labels, 'rpt_eng_generated_at')}: {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    )
    ws.cell(row_idx, 1).font = Font(italic=True, size=9, color="888888")
    row_idx += 2

    # KPIs
    kpis = report_data.get("kpis", [])
    if kpis:
        ws.cell(row_idx, 1, _lbl(labels, "rpt_eng_section_summary"))
        ws.cell(row_idx, 1).font = Font(bold=True, size=11)
        row_idx += 1
        for kpi in kpis:
            ws.cell(row_idx, 1, kpi.get("label", ""))
            ws.cell(row_idx, 2, kpi.get("value", ""))
            ws.cell(row_idx, 2).font = kpi_font
            if kpi.get("sub"):
                ws.cell(row_idx, 3, kpi["sub"])
                ws.cell(row_idx, 3).font = Font(size=9, color="888888")
            row_idx += 1
        row_idx += 1

    # Sections / Tabellen
    for section in report_data.get("sections", []):
        ws.cell(row_idx, 1, section.get("title", ""))
        ws.cell(row_idx, 1).font = Font(bold=True, size=12)
        row_idx += 1

        columns = section.get("columns", [])
        rows    = section.get("rows", [])

        if columns:
            for col_idx, col in enumerate(columns, start=1):
                cell = ws.cell(row_idx, col_idx, col)
                cell.fill = header_fill
                cell.font = header_font
                cell.alignment = Alignment(horizontal="left")
            row_idx += 1

        alt_fill = PatternFill("solid", fgColor=alt_hex)
        for i, row in enumerate(rows):
            for col_idx, cell_val in enumerate(row, start=1):
                # Delta-HTML aus trend-Report strippen
                val = _strip_delta_html(cell_val) if isinstance(cell_val, str) else cell_val
                cell = ws.cell(row_idx, col_idx, val)
                cell.border = thin_border
                if i % 2 == 0:
                    cell.fill = alt_fill
            row_idx += 1
        row_idx += 2

    # Spaltenbreiten anpassen
    for col in ws.columns:
        max_len = 0
        col_letter = col[0].column_letter
        for cell in col:
            try:
                if cell.value:
                    max_len = max(max_len, len(str(cell.value)))
            except Exception:
                pass
        ws.column_dimensions[col_letter].width = min(max_len + 4, 40)

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def generate_report(
    query_type: str,
    data: Any,
    period: str,
    layout: Optional[dict] = None,
    output_formats: Optional[list[str]] = None,
    currency: str = "€",
    labels: Optional[dict] = None,
    lang: str = "en",
    query_params: Optional[dict] = None,
) -> dict[str, str]:
    """
    Erzeugt alle angeforderten Ausgabeformate für einen Report (i18n-aware).

    Args:
        query_type:     "print_stats" | "cost_report" | "top_users" | "top_printers" |
                        "trend" | "anomalies"
        data:           Query-Ergebnis (Liste oder Dict für trend)
        period:         Zeitraum-Label
        layout:         Layout/Theme-Dict (wird durch normalize_layout() normalisiert)
        output_formats: Liste: "html" | "csv" | "json" | "pdf" | "xlsx"
        currency:       Währungssymbol (für Kosten-Formatierung)
        labels:         i18n-Dict mit rpt_eng_*-Keys (aus TRANSLATIONS[locale])
        lang:           ISO-Sprachcode (für `<html lang>`)

    Returns:
        Dict {format: content}
    """
    output_formats = output_formats or ["html"]
    layout = normalize_layout(layout or {})
    query_params = query_params or {}
    group_by = str(query_params.get("group_by") or "day")

    # Währung aus Layout überschreiben wenn gesetzt (Theme-Config)
    cur_key = layout.get("currency")
    if cur_key and cur_key in CURRENCIES_BY_KEY:
        currency = CURRENCIES_BY_KEY[cur_key]["symbol"]

    # Report-Datenstruktur bauen
    if query_type == "print_stats":
        report_data = build_print_stats_report(
            data, period, layout, group_by=group_by, labels=labels)
        title = _lbl(labels, "rpt_eng_title_print_stats")
    elif query_type == "cost_report":
        report_data = build_cost_report_report(
            data, period, layout, currency, group_by=group_by, labels=labels)
        title = _lbl(labels, "rpt_eng_title_cost_report")
    elif query_type == "top_users":
        report_data = build_top_users_report(data, period, currency, labels=labels)
        title = _lbl(labels, "rpt_eng_title_top_users")
    elif query_type == "top_printers":
        report_data = build_top_printers_report(data, period, currency, labels=labels)
        title = _lbl(labels, "rpt_eng_title_top_printers")
    elif query_type == "trend":
        report_data = build_trend_report(data, currency, labels=labels)
        title = _lbl(labels, "rpt_eng_title_trend")
    elif query_type == "hour_dow_heatmap":
        report_data = build_hour_dow_heatmap_report(data, period, layout, labels=labels)
        title = _lbl(labels, "rpt_eng_title_hour_dow_heatmap")
    else:
        # Stufe 2: Generische Tabellen-Ausgabe (Spalten aus erster Zeile).
        # v3.7.9: i18n-Titel aus rpt_eng_title_<type> wenn vorhanden, sonst
        # humanisiertes Fallback \u2014 so bekommt z.B. service_desk einen
        # vern\u00fcnftigen Titel in der jeweiligen UI-Sprache.
        # v3.7.10: DB-Spaltennamen mit _translate_col(lang) \u00fcbersetzen, damit
        # im HTML/PDF/XLSX keine rohen Namen wie "job_id", "print_time" mehr
        # auftauchen.
        _keys_raw = list(data[0].keys()) if data else []
        _keys_loc = [_translate_col(k, lang) for k in _keys_raw]
        report_data = {
            "kpis": [],
            "sections": [{
                "title":   _lbl(labels, "rpt_eng_section_details"),
                "columns": _keys_loc,
                "rows":    [[str(v) for v in r.values()] for r in data] if data else [],
            }],
        }
        title_key = f"rpt_eng_title_{query_type}"
        if labels and title_key in labels:
            title = labels[title_key]
        else:
            title = query_type.replace("_", " ").title()

    # Optional: Environmental Impact Section
    if layout.get("show_env_impact"):
        totals = report_data.get("_totals", {})
        total_pages = totals.get("total_pages", 0)
        saved = totals.get("saved_sheets", 0)
        if total_pages > 0:
            env = compute_env_impact(total_pages, saved_sheets=saved)
            report_data.setdefault("sections", []).append(
                _build_env_impact_section(env, labels=labels)
            )

    # Gewünschte Formate generieren
    company = layout.get("company_name", "").strip()
    title_full = f"{company} – {title}" if company else title
    results: dict[str, Any] = {}

    if "html" in output_formats:
        results["html"] = render_html(title_full, period, report_data, layout, labels=labels, lang=lang)
    if "csv" in output_formats:
        raw = data if isinstance(data, list) else []
        _csv = render_csv(raw)
        if not _csv:
            hint = _lbl(labels, "rpt_eng_no_data")
            results["csv"] = f'{_lbl(labels, "rpt_eng_period")},Info\r\n"{period}","{hint}"\r\n'
        else:
            results["csv"] = _csv
    if "json" in output_formats:
        results["json"] = render_json(data)
    if "pdf" in output_formats:
        try:
            results["pdf"] = render_pdf(title_full, period, report_data, layout, labels=labels)
        except Exception as e:
            logger.error("PDF-Generierung fehlgeschlagen: %s", e, exc_info=True)
            results["pdf_error"] = str(e)
    if "xlsx" in output_formats:
        try:
            results["xlsx"] = render_xlsx(title_full, period, report_data, layout, labels=labels)
        except Exception as e:
            logger.error("XLSX-Generierung fehlgeschlagen: %s", e, exc_info=True)
            results["xlsx_error"] = str(e)

    return results
