
BUILTIN_PROFILES = [
    {
        "id": "builtin-plain-base64",
        "is_builtin": True,
        "tenant_id": "",
        "name": "Plain Base64",
        "vendor": "Generic",
        "reader_model": "Any",
        "mode": "text",
        "description": "Encode visible text card value as Base64.",
        "rules_json": {
            "strip_separators": False,
            "input_mode": "text",
            "submit_mode": "base64_text",
            "base64_source": "raw",
        },
    },
    {
        "id": "builtin-cleanup-base64",
        "is_builtin": True,
        "tenant_id": "",
        "name": "Cleanup + Base64",
        "vendor": "Generic",
        "reader_model": "Any",
        "mode": "cleanup",
        "description": "Remove separators and encode cleaned value as Base64.",
        "rules_json": {
            "strip_separators": True,
            "input_mode": "text",
            "submit_mode": "base64_text",
            "base64_source": "normalized",
        },
    },
    {
        "id": "builtin-hex-decimal-helper",
        "is_builtin": True,
        "tenant_id": "",
        "name": "HEX / Decimal Helper",
        "vendor": "Generic",
        "reader_model": "Any",
        "mode": "helper",
        "description": "Use for reader output shown as hex bytes or decimal values.",
        "rules_json": {
            "strip_separators": True,
            "input_mode": "auto",
            "submit_mode": "raw",
        },
    },
    {
        "id": "builtin-ysoft-decimal-reversed",
        "is_builtin": True,
        "tenant_id": "",
        "name": "YSoft Decimal Reversed",
        "vendor": "YSoft",
        "reader_model": "Any",
        "mode": "decimal_reversed",
        "description": "Interpret input as hex/decimal and send decimal of reversed hex bytes.",
        "rules_json": {
            "strip_separators": True,
            "input_mode": "auto",
            "submit_mode": "decimal_reversed",
        },
    },
    {
        "id": "builtin-lowercase-base64",
        "is_builtin": True,
        "tenant_id": "",
        "name": "Lowercase + Base64",
        "vendor": "Generic",
        "reader_model": "Any",
        "mode": "lowercase_base64",
        "description": "Lowercase the visible value first, then Base64 encode it.",
        "rules_json": {
            "strip_separators": False,
            "input_mode": "text",
            "submit_mode": "base64_text",
            "lowercase": True,
            "base64_source": "normalized",
        },
    },
    {
        "id": "builtin-double-base64",
        "is_builtin": True,
        "tenant_id": "",
        "name": "Double Base64",
        "vendor": "Generic",
        "reader_model": "Any",
        "mode": "double_base64",
        "description": "For workflows that expect Base64 of a Base64 text value.",
        "rules_json": {
            "strip_separators": False,
            "input_mode": "text",
            "submit_mode": "base64_text",
            "double_base64": True,
            "base64_source": "raw",
        },
    },
    {
        "id": "builtin-ysoft-konica-mifare",
        "is_builtin": True,
        "tenant_id": "",
        "name": "YSoft Konica Mifare",
        "vendor": "YSoft",
        "reader_model": "Konica Mode",
        "mode": "base64_debug_suffix",
        "description": "Use raw hex text, append 8x y-diaeresis as seen in Logic App debug output, then Base64 encode.",
        "rules_json": {
            "strip_separators": True,
            "input_mode": "text",
            "submit_mode": "base64_text",
            "base64_source": "raw",
            "base64_suffix_hex": "FF",
            "base64_suffix_count": 8,
        },
    },
    {
        "id": "builtin-keyboard-clean-base64",
        "is_builtin": True,
        "tenant_id": "",
        "name": "Keyboard Clean + Base64",
        "vendor": "Generic",
        "reader_model": "Keyboard",
        "mode": "keyboard_base64",
        "description": "Remove common helper characters like underscore, asterisk, colon and dash before Base64 encoding.",
        "rules_json": {
            "strip_separators": True,
            "remove_chars": "_*",
            "input_mode": "text",
            "submit_mode": "base64_text",
            "base64_source": "normalized",
        },
    },
    {
        "id": "builtin-baltech-decimal-base64",
        "is_builtin": True,
        "tenant_id": "",
        "name": "Baltech Decimal + Base64",
        "vendor": "Baltech",
        "reader_model": "Default Binary",
        "mode": "decimal_base64",
        "description": "Treat the visible value as decimal/text and Base64 encode the cleaned value for Printix Card API.",
        "rules_json": {
            "strip_separators": False,
            "input_mode": "text",
            "submit_mode": "base64_text",
            "base64_source": "raw",
        },
    },
    {
        "id": "builtin-rfideas-hid-keyboard",
        "is_builtin": True,
        "tenant_id": "",
        "name": "RFIDeas HID Keyboard",
        "vendor": "RFIDeas",
        "reader_model": "Y7xxx",
        "mode": "keyboard_base64",
        "description": "Typical keyboard-style HID output: keep the visible reader value and Base64 encode it for Printix.",
        "rules_json": {
            "strip_separators": False,
            "input_mode": "text",
            "submit_mode": "base64_text",
            "base64_source": "raw",
        },
    },
    {
        "id": "builtin-elatec-keyboard",
        "is_builtin": True,
        "tenant_id": "",
        "name": "Elatec Keyboard",
        "vendor": "Elatec",
        "reader_model": "TWN4",
        "mode": "keyboard_base64",
        "description": "Typical Elatec keyboard reader output: encode the visible card value directly as Base64.",
        "rules_json": {
            "strip_separators": False,
            "input_mode": "text",
            "submit_mode": "base64_text",
            "base64_source": "raw",
        },
    },
    {
        "id": "builtin-elatec-keyboard-clean",
        "is_builtin": True,
        "tenant_id": "",
        "name": "Elatec Keyboard Clean",
        "vendor": "Elatec",
        "reader_model": "TWN4 Keyboard",
        "mode": "keyboard_base64",
        "description": "Keyboard workflow with cleanup of helper characters such as underscore, asterisk, colon and dash before Base64 encoding.",
        "rules_json": {
            "strip_separators": True,
            "remove_chars": "_*",
            "input_mode": "text",
            "submit_mode": "base64_text",
            "base64_source": "normalized",
        },
    },
    {
        "id": "builtin-inepro-keyboard",
        "is_builtin": True,
        "tenant_id": "",
        "name": "Inepro Spider Keyboard",
        "vendor": "Inepro",
        "reader_model": "Spider",
        "mode": "keyboard_base64",
        "description": "Typical Inepro Spider keyboard output encoded directly as Base64.",
        "rules_json": {
            "strip_separators": False,
            "input_mode": "text",
            "submit_mode": "base64_text",
            "base64_source": "raw",
        },
    },
    {
        "id": "builtin-inepro-keyboard-lower",
        "is_builtin": True,
        "tenant_id": "",
        "name": "Inepro Spider Lowercase",
        "vendor": "Inepro",
        "reader_model": "Spider",
        "mode": "keyboard_lowercase_base64",
        "description": "Ricoh-style Inepro keyboard workflow: lowercase the visible value first, then Base64 encode it.",
        "rules_json": {
            "strip_separators": False,
            "input_mode": "text",
            "submit_mode": "base64_text",
            "lowercase": True,
            "base64_source": "normalized",
        },
    },
    {
        "id": "builtin-rfideas-lowercase",
        "is_builtin": True,
        "tenant_id": "",
        "name": "RFIDeas Lowercase Keyboard",
        "vendor": "RFIDeas",
        "reader_model": "Y7xxx / MiCard",
        "mode": "keyboard_lowercase_base64",
        "description": "Lowercase the keyboard-style reader value before Base64 encoding, as seen in some Ricoh workflows.",
        "rules_json": {
            "strip_separators": False,
            "input_mode": "text",
            "submit_mode": "base64_text",
            "lowercase": True,
            "base64_source": "normalized",
        },
    },
    {
        "id": "builtin-micard-rfideas",
        "is_builtin": True,
        "tenant_id": "",
        "name": "MiCard RFIDeas",
        "vendor": "MiCard",
        "reader_model": "RFIDeas",
        "mode": "keyboard_base64",
        "description": "Encode the visible MiCard / RFIDeas value directly as Base64.",
        "rules_json": {
            "strip_separators": False,
            "input_mode": "text",
            "submit_mode": "base64_text",
            "base64_source": "raw",
        },
    },
    {
        "id": "builtin-hp-mfp24",
        "is_builtin": True,
        "tenant_id": "",
        "name": "HP MFP24",
        "vendor": "HP",
        "reader_model": "X3D03A/B",
        "mode": "hex2base64",
        "description": "HP MFP24 workflows typically take the visible card value and Base64 encode it directly.",
        "rules_json": {
            "strip_separators": False,
            "input_mode": "text",
            "submit_mode": "base64_text",
            "base64_source": "raw",
        },
    },
    {
        "id": "builtin-baltech-double-base64",
        "is_builtin": True,
        "tenant_id": "",
        "name": "Baltech Double Base64",
        "vendor": "Baltech",
        "reader_model": "Default Binary",
        "mode": "double_base64",
        "description": "Ricoh-style Baltech workflow that expects Base64 of an already Base64-encoded visible value.",
        "rules_json": {
            "strip_separators": False,
            "input_mode": "text",
            "submit_mode": "base64_text",
            "double_base64": True,
            "base64_source": "raw",
        },
    },
    {
        "id": "builtin-kyocera-elatec-double",
        "is_builtin": True,
        "tenant_id": "",
        "name": "Kyocera Elatec Double Base64",
        "vendor": "Elatec",
        "reader_model": "TWN4 Keyboard",
        "mode": "double_base64",
        "description": "Kyocera note from the Excel: Base64 the keyboard value and Base64 it once again.",
        "rules_json": {
            "strip_separators": False,
            "input_mode": "text",
            "submit_mode": "base64_text",
            "double_base64": True,
            "base64_source": "raw",
        },
    },
]

def get_builtin_profiles():
    return [dict(p) for p in BUILTIN_PROFILES]
